//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class HRMS_TRAINING_MATERIAL_MS
    {
        [DisplayName("Material Code")]
        public long Material_ID { get; set; }
        [Required]
        [DisplayName("Material Name")]
        public string Material_Name { get; set; }
        [Required]
        [DisplayName("Default Rate")]
        public decimal Material_Rate { get; set; }
        [DisplayName("Remark")]
        public string Material_Remarks { get; set; }
        [DisplayName("Active")]
        public bool Material_IsActive { get; set; }
    }
}
