//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMS_Faculty_MS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HRMS_Faculty_MS()
        {
            this.HRMS_ProgramFaculty = new HashSet<HRMS_ProgramFaculty>();
        }
    
        public long ID { get; set; }
        public string FacultyType { get; set; }
        public Nullable<long> EMP_ID { get; set; }
        public string External_Name { get; set; }
        public string PAN_No { get; set; }
        public string ServiceTaxNo { get; set; }
        public string Qualification { get; set; }
        public string Contact { get; set; }
        public string Email { get; set; }
        public string Remark { get; set; }
        public bool IsActive { get; set; }
        public string Empty { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRMS_ProgramFaculty> HRMS_ProgramFaculty { get; set; }
    }
}
