//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class HRMS_TRAINING_SKILL_MS
    {
        [DisplayName("Skill Code")]
        public long Skill_ID { get; set; }
        [Required]
        [DisplayName("Skill Name")]

        public string Skill_Name { get; set; }
        [DisplayName("Remark")]
        public string Skill_Remark { get; set; }
    }
}
