//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMS_TravelGroupType_MS
    {
        public long ID { get; set; }
        public long Mode_ID { get; set; }
        public System.DateTime Date { get; set; }
        public string Group_Name { get; set; }
    
        public virtual HRMS_TravelMode_MS HRMS_TravelMode_MS { get; set; }
    }
}
