//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMS_TrainingReview
    {
        public long ID { get; set; }
        public long ProgramID { get; set; }
        public long Emp_ID { get; set; }
        public long QuestionID { get; set; }
        public Nullable<int> NonDescriptive { get; set; }
        public string Descriptive { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string OtherComments { get; set; }
        public bool IsWorthy { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual HRMS_Evalution_Question HRMS_Evalution_Question { get; set; }
        public virtual HRMS_ProgramDetail HRMS_ProgramDetail { get; set; }
    }
}
