//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMS_TRAVEL_MEAL_EXPENSE_MS
    {
        public long Meal_Expense_ID { get; set; }
        public string Meal_Expense_NM { get; set; }
        public bool Meal_Expense_Status { get; set; }
    }
}
