//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMS_EMP_GRA_POL
    {
        public long Emp_Gra_Pol_ID { get; set; }
        public long Emp_ID { get; set; }
        public long Gra_ID { get; set; }
        public long Pol_ID { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual HRMS_CATEGORY_GRADE HRMS_CATEGORY_GRADE { get; set; }
        public virtual HRMS_TravelGroupType_MS HRMS_TravelGroupType_MS { get; set; }
    }
}
