//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMS_Travel_Expense_App
    {
        public long ID { get; set; }
        public long Travel_App_ID { get; set; }
        public System.DateTime Travel_Date { get; set; }
        public string Journey_Mode { get; set; }
        public string From_Place { get; set; }
        public string To_Place { get; set; }
        public Nullable<decimal> Distance { get; set; }
        public decimal Amount { get; set; }
        public string Purpose { get; set; }
        public string FileName { get; set; }
        public string FileUrl { get; set; }
        public long EMP_ID { get; set; }
        public Nullable<int> Status { get; set; }
        public bool DateLimit { get; set; }
        public Nullable<int> Warning { get; set; }
    
        public virtual HRMS_Travel_Application HRMS_Travel_Application { get; set; }
        public virtual Accounts Accounts { get; set; }
    }
}
