//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMS_TRAVEL_MODE_CONFIG
    {
        public long Travel_Mode_ID { get; set; }
        public long Travel_Group { get; set; }
        public string Travel_Policy { get; set; }
        public bool Travel_By_Auto { get; set; }
        public bool Travel_By_Taxi { get; set; }
        public decimal Travel_Local_Conveyance_Max { get; set; }
        public string Travel_Emp_Grade { get; set; }
    }
}
