//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class HRMS_Evalution_Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HRMS_Evalution_Question()
        {
            this.HRMS_TrainingReview = new HashSet<HRMS_TrainingReview>();
        }
    
        public long ID { get; set; }
        [Required]
        [MaxLength(500, ErrorMessage = "Question can have 500 characters maximum!")]
        public string Question { get; set; }
        public bool IsDescription { get; set; }
        public long Header_ID { get; set; }
    
        public virtual HRMS_TrainingEvalution_Header HRMS_TrainingEvalution_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRMS_TrainingReview> HRMS_TrainingReview { get; set; }
    }
}
