//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMS_TRAVEL_OTHER_DETAILS_MS
    {
        public long Travel_Other_Details_ID { get; set; }
        public string Travel_Other_Details_NM { get; set; }
    }
}
