//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMS_ProgramFaculty
    {
        public long ID { get; set; }
        public string FacultyName { get; set; }
        public string Email { get; set; }
        public long FacultyID { get; set; }
        public long ProgramID { get; set; }
    
        public virtual HRMS_Faculty_MS HRMS_Faculty_MS { get; set; }
        public virtual HRMS_ProgramDetail HRMS_ProgramDetail { get; set; }
    }
}
