//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMS_Evalution_Question
    {
        public long ID { get; set; }
        public string Question { get; set; }
        public bool IsDescription { get; set; }
        public long Header_ID { get; set; }
    
        public virtual HRMS_TrainingEvalution_Header HRMS_TrainingEvalution_Header { get; set; }
    }
}
