//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class HRMS_Faculty_MS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HRMS_Faculty_MS()
        {
            this.HRMS_ProgramFaculty = new HashSet<HRMS_ProgramFaculty>();
        }
    
        public long ID { get; set; }
        [Required]
        [DisplayName("Faculty Name")]
        public string FacultyType { get; set; }
        [DisplayName("Employee ID")]
        public Nullable<long> EMP_ID { get; set; }
        [DisplayName("Faculty Name")]
        [MaxLength(50, ErrorMessage = "Name can have 50 characters maximum!")]
        public string External_Name { get; set; }
        [DisplayName("PanCard No")]
        [RegularExpression(@"^[A-Za-z0-9_ ]*$", ErrorMessage = "Only AlphNumeric values are allowed!")]
        public string PAN_No { get; set; }
        [RegularExpression(@"^[A-Za-z0-9_ ]*$", ErrorMessage = "Only AlphNumeric values are allowed!")]
        [DisplayName("Service Tax No")]
        public string ServiceTaxNo { get; set; }
        [RegularExpression(@"^[A-Za-z0-9_ ]*$", ErrorMessage = "Only AlphNumeric values are allowed!")]
        public string Qualification { get; set; }
        [Required]
        [RegularExpression(@"^[0-9]{10}$", ErrorMessage = "Contact must be in valid format")]
        public string Contact { get; set; }
        [Required]
        [RegularExpression(@"^\w+@[a-zA-Z_]+?\.[a-zA-Z]{2,3}$", ErrorMessage = "Enter a valid email !")]
        public string Email { get; set; }
        [MaxLength(100, ErrorMessage = "Remarks can have 50 characters maximum!")]
        public string Remark { get; set; }
        public bool IsActive { get; set; }
        [MaxLength(100, ErrorMessage = "Address can have 50 characters maximum!")]
        public string Empty { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRMS_ProgramFaculty> HRMS_ProgramFaculty { get; set; }
    }
}
