//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class HRMS_DESG_MS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HRMS_DESG_MS()
        {
            this.HRMS_Emp_Details = new HashSet<HRMS_Emp_Details>();
            this.HRMS_Travel_Application = new HashSet<HRMS_Travel_Application>();
            this.HRMS_Training_Request_Application = new HashSet<HRMS_Training_Request_Application>();
            this.HRMS_TrainingApproval = new HashSet<HRMS_TrainingApproval>();
            this.HRMS_Program_Attandance = new HashSet<HRMS_Program_Attandance>();
        }

        [Display(Name = "ID")]
        public long Desg_Id { get; set; }
        [Required]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Use letters only please")]
        [MaxLength(50, ErrorMessage = "Designation Name can have 50 characters maximum!")]

        [Display(Name = "Designation Name")]
        public string Desg_Name { get; set; }
        [Required]
        [RegularExpression(@"^[a-zA-Z]+$", ErrorMessage = "Use letters only please")]
        [MaxLength(10, ErrorMessage = "Designation ShortName can have 10 characters maximum!")]

        [Display(Name = "Designation ShortName")]
        public string Desg_Short_Name { get; set; }
        public Nullable<long> Desg_Parent_ID { get; set; }
        public bool IsActive { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<long> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRMS_Emp_Details> HRMS_Emp_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRMS_Travel_Application> HRMS_Travel_Application { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRMS_Training_Request_Application> HRMS_Training_Request_Application { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRMS_TrainingApproval> HRMS_TrainingApproval { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HRMS_Program_Attandance> HRMS_Program_Attandance { get; set; }
    }
}
