//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMS_TRAINING_MATERIALSET
    {
        public decimal MaterialSet_Budget_Amt { get; set; }
        public decimal MaterialSet_Actual_Amt { get; set; }
        public long MaterialSet_ID { get; set; }
        public long ProgDet_ID { get; set; }
        public long Material_ID { get; set; }
        public string Material_Name { get; set; }
        public string Bud_Act { get; set; }
        public long MaterialSet_Qty { get; set; }
        public decimal MaterialSet_Rate { get; set; }
        public decimal MaterialSet_Amt { get; set; }
    
        public virtual HRMS_ProgramDetail HRMS_ProgramDetail { get; set; }
        public virtual HRMS_TRAINING_MATERIAL_MS HRMS_TRAINING_MATERIAL_MS { get; set; }
    }
}
