//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMS_TRAINING_SKILLSET
    {
        public long SkillSet_ID { get; set; }
        public long ProgDetail_ID { get; set; }
        public long Skill_ID { get; set; }
        public string Skill_Name { get; set; }
    
        public virtual HRMS_ProgramDetail HRMS_ProgramDetail { get; set; }
        public virtual HRMS_TRAINING_SKILL_MS HRMS_TRAINING_SKILL_MS { get; set; }
    }
}
