//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMS_TRAVEL_MILEAGE_CONFIG
    {
        public long Travel_Mileage_ID { get; set; }
        public long Travel_Group { get; set; }
        public string Travel_Policy { get; set; }
        public decimal Travel_Mileage_Two { get; set; }
        public decimal Travel_Mileage_Four { get; set; }
        public decimal Travel_Mileage_Moped { get; set; }
        public string Travel_Mileage_Emp_Grade { get; set; }
    }
}
