//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class HRMS_Travel_Application
    {
        public long ID { get; set; }

        public long Travel_App_Type { get; set; }
        [Required]
        [Display(Name = "Travel Application Date")]
        // [DataType(DataType.Date, ErrorMessage = "Only Date allowed")]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Travel_Application_Date { get; set; }
        public long emp_id { get; set; }
        public Nullable<long> Designation { get; set; }
        public Nullable<long> Grade { get; set; }
        [Required]
        [Display(Name ="Travel Type")]
        public int Travel_Type { get; set; }
        [Required]
        [Display(Name = "Travel Purpose")]
        public long Travel_Purpose { get; set; }
        [Required]
        [Display(Name = "From_Date")]
        [DataType(DataType.Date, ErrorMessage = "Only Date allowed")]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> From_Date { get; set; }
        [Required]
        [Display(Name = "To Date")]
        [DataType(DataType.Date, ErrorMessage = "Only Date allowed")]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> To_Date { get; set; }

        [RegularExpression(@"^[A-Za-z0-9_ ]*$", ErrorMessage = "Only AlphNumeric values are allowed!")]

        public string Remark { get; set; }
        
        public int Status { get; set; }
        public Nullable<long> Approved_by { get; set; }
        [Display(Name = "Approved Date")]
        // [DataType(DataType.Date, ErrorMessage = "Only Date allowed")]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Approved_date { get; set; }
        [Display(Name ="Approval Remark")]
        [RegularExpression(@"^[A-Za-z0-9_ ]*$", ErrorMessage = "Only AlphNumeric values are allowed!")]

        public string Approval_Remark { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual Accounts Accounts1 { get; set; }
        public virtual HRMS_CATEGORY_GRADE HRMS_CATEGORY_GRADE { get; set; }
        public virtual HRMS_DESG_MS HRMS_DESG_MS { get; set; }
        public virtual HRMS_Travel_Purpose HRMS_Travel_Purpose { get; set; }
        public virtual HRMS_Travel_type HRMS_Travel_type { get; set; }
        public virtual HRMS_TravelMode_MS HRMS_TravelMode_MS { get; set; }
    }
}
