//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class HRMS_EMP_PHOTO_SIGN
    {
        public long Emp_Photos_ID { get; set; }
        public long Emp_ID { get; set; }
        public string Emp_Photo_Title { get; set; }
        public string Emp_Photo_Path { get; set; }
        public string Emp_Sign_Title { get; set; }
        public string Emp_Sign_Path { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
        public HttpPostedFileBase SignFile { get; set; }


        public virtual Accounts Accounts { get; set; }
    }
}
