//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HRMS_Program_Attandance
    {
        public long ID { get; set; }
        public long ProgramID { get; set; }
        public long EmployeeID { get; set; }
        public System.DateTime AttandenceDate { get; set; }
        public string EmpName { get; set; }
        public string IsPresent { get; set; }
        public Nullable<long> DesignationID { get; set; }
        public Nullable<long> DepartmentID { get; set; }
        public string Gender { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual HRMS_DEPT HRMS_DEPT { get; set; }
        public virtual HRMS_DESG_MS HRMS_DESG_MS { get; set; }
        public virtual HRMS_Program_Attandance HRMS_Program_Attandance1 { get; set; }
        public virtual HRMS_Program_Attandance HRMS_Program_Attandance2 { get; set; }
        public virtual HRMS_ProgramDetail HRMS_ProgramDetail { get; set; }
    }
}
