//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sample
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public long Emp_ID { get; set; }
    
        public virtual Accounts Accounts { get; set; }
    }
}
